SESSION 4 - Data Collection using Pandas (Part 1)Topics Covered:What is pandas & why DS heavily depends on itTypes of data filesCSV, Excel, TSVJSONImporting
datasetspd.read_csv()pd.read_excel()Handling separators (comma, semicolon, tab)Reading large fileschunksize parameteriterating through file
chunksDetecting data issues earlydf.info()df.describe(include='all')

In [1]:
import numpy as np 
import pandas as pd


TASKS


1. Download a sample CSV file of IPL cricket match scores from Kaggle or any public dataset, and use pd.read_csv to load it into a DataFrame. Print the first 5 rows to verify the data.

In [3]:
## load a file into the dataframe ;- 

dataset = pd.read_csv("F:/Tops_assignment/Python_Library/datasets/ipl/deliveries.csv")
dataset
dataset.head()

,match_id,inning,batting_team,bowling_team,over,ball,batter,bowler,non_striker,batsman_runs,extra_runs,total_runs,extras_type,is_wicket,player_dismissed,dismissal_kind,fielder
0,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,1,SC Ganguly,P Kumar,BB McCullum,0,1,1,legbyes,0,NaN,NaN,NaN
1,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,2,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN
2,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,BB McCullum,P Kumar,SC Ganguly,0,1,1,wides,0,NaN,NaN,NaN
3,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,4,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN
4,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,5,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN

2. Find a small JSON dataset of trending songs (for example, from Spotify's API samples or any open JSON file), and use pd.read_json0 to import it into a DataFrame. Display the DataFrame's column names and data types
using df.info0.

In [5]:
dataset1 = pd.read_json("F:\Tops_assignment\Python_Library\datasets\json_spotify_songs\spotify_trending_songs.json")
dataset1
dataset1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   rank              10 non-null     int64
 1   song_name         10 non-null     object
 2   artist            10 non-null     object
 3   album             10 non-null     object
 4   genre             10 non-null     object
 5   streams_millions  10 non-null     int64
 6   release_year      10 non-null     int64
dtypes: int64(3), object(4)
memory usage: 692.0+ bytes


3. You have a TSV (tab-separated values) file containing Zomato restaurant data. Use pd.read_csv() with the correct separator to load the data, and then use df.describe(include='all') to generate summary statistics.

        Hint: The separator for TSV files is '\t'.

In [12]:
dataset3 = pd.read_csv("F:/Tops_assignment/Python_Library/datasets/tsv_zomato/zomato_restaurants.tsv" ,sep = "\t")
dataset3
dataset3.describe(include= 'all') # if all will not be there then only the field with values will be showed

         Restaurant       City       Cuisine     Rating        Votes
count            10         10            10  10.000000    10.000000
unique           10          8            10        NaN          NaN
top     Spice Villa  Ahmedabad  North Indian        NaN          NaN
freq              1          3             1        NaN          NaN
mean            NaN        NaN           NaN   4.260000  1178.000000
std             NaN        NaN           NaN   0.236643   480.573731
min             NaN        NaN           NaN   3.900000   650.000000
25%             NaN        NaN           NaN   4.100000   862.500000
50%             NaN        NaN           NaN   4.250000  1040.000000
75%             NaN        NaN           NaN   4.475000  1425.000000
max             NaN        NaN           NaN   4.600000  2100.000000


4. Download a large Excel file (at least 10,000 rows) of Flipkart product listings. Use pd.read_excel() with the chunksize parameter to read the file in chunks of 2000 rows, and print the number of rows in each chunk as you
iterate.

### Interview Question

Why does read_csv() support chunksize but read_excel() doesn't?

CSV files are plain text and can be streamed efficiently.
Excel files (.xlsx) are compressed workbook formats that usually need to be loaded before parsing.
Therefore, Pandas provides chunksize for CSVs but not for Excel files.

In [18]:
dataset4 = pd.read_excel("F:/Tops_assignment/Python_Library/datasets/flipkart_product_excel/flipkart_product_listings_10000.xlsx")
dataset4

chunk_size = 2000

for i in range(0 , len(dataset4) ,chunk_size):
    chunk = dataset4.iloc[i:i+chunk_size]
    print(f"Chunk {(i//chunk_size) + 1 }: {len(chunk)} row")

Chunk 1: 2000 row
Chunk 2: 2000 row
Chunk 3: 2000 row
Chunk 4: 2000 row
Chunk 5: 2000 row


5. Use ChatGPT or Copilot to generate a Python code snippet that reads a semicolon-separated CSV of Paytm transactions, detects missing values, and prints out which columns have nulls. Test the code with a small
sample file and fix any errors you encounter.

In [25]:
## we will load the dataset first 

dataset5 = pd.read_csv("F:\Tops_assignment\Python_Library\datasets\paytm\PhonePayIndia.csv")
dataset5.head()
print(dataset5.info())
print("\n\n")
print(dataset5.describe())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11741 entries, 0 to 11740
Data columns (total 11 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Unnamed: 0            11741 non-null  int64
 1   reviewId              11741 non-null  object
 2   userName              11741 non-null  object
 3   userImage             11741 non-null  object
 4   content               11741 non-null  object
 5   score                 11741 non-null  int64
 6   thumbsUpCount         11741 non-null  int64
 7   reviewCreatedVersion  9605 non-null   object
 8   at                    11741 non-null  object
 9   replyContent          2936 non-null   object
 10  repliedAt             2936 non-null   object
dtypes: int64(3), object(8)
memory usage: 1009.1+ KB
None



        Unnamed: 0         score  thumbsUpCount
count  11741.00000  11741.000000   11741.000000
mean    5870.00000      4.113534       0.208074
std     3389.47909      1.460953       5.665902
min        0.00000      1.000000       0.000000
25%     2935.00000      4.000000       0.000000
50%     5870.00000      5.000000       0.000000
75%     8805.00000      5.000000       0.000000
max    11740.00000      5.000000     353.000000

In [26]:
print(dataset5.isnull().sum()) # this will print all the colimn and how many missing valeus are there in those column

Unnamed: 0                 0
reviewId                   0
userName                   0
userImage                  0
content                    0
score                      0
thumbsUpCount              0
reviewCreatedVersion    2136
at                         0
replyContent            8805
repliedAt               8805
dtype: int64

In [28]:
## another way to print only the column that have missing values 
print(dataset5.columns[dataset5.isnull().any()])
## this will return a list of the clumns that have missing values

Index(['reviewCreatedVersion', 'replyContent', 'repliedAt'], dtype='object')

### now the next step will be to fill the issisng values with the data