SESSION 7 - Data Cleaning (Part 2: Outliers & Data Types)Topics Covered:Outlier detectionBoxplot methodZ-score methodIQR methodOutlier
treatmentWinsorizationLog transformCapping and flooringData type conversionsastype()Converting objects ? numericFixing bool/Category/int mixupsPractical
cleanup tasks:Date parsingFixing incorrect string formats

In [2]:
import pandas as pd 
import numpy as np



TASKS


1. Given a CSV file containing Zomato restaurant ratings, use pandas to detect outliers in the 'user_rating' column using the IQR method and print the indices of the detected outliers.

In [ ]:
dataset = pd.read_csv("F:\Tops_assignment\Python_Library\datasets\zomato.csv\zomato.csv")

In [5]:
dataset.head()

,url,address,name,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,approx_cost(for two people),reviews_list,menu_item,listed_in(type),listed_in(city)
0,https://www.zomato.com/bangalore/jalsa-banasha...,"942, 21st Main Road, 2nd Stage, Banashankari, ...",Jalsa,Yes,Yes,4.1/5,775,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",800,"[('Rated 4.0', 'RATED\n A beautiful place to ...",[],Buffet,Banashankari
1,https://www.zomato.com/bangalore/spice-elephan...,"2nd Floor, 80 Feet Road, Near Big Bazaar, 6th ...",Spice Elephant,Yes,No,4.1/5,787,080 41714161,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",800,"[('Rated 4.0', 'RATED\n Had been here for din...",[],Buffet,Banashankari
2,https://www.zomato.com/SanchurroBangalore?cont...,"1112, Next to KIMS Medical College, 17th Cross...",San Churro Cafe,Yes,No,3.8/5,918,+91 9663487993,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",800,"[('Rated 3.0', ""RATED\n Ambience is not that ...",[],Buffet,Banashankari
3,https://www.zomato.com/bangalore/addhuri-udupi...,"1st Floor, Annakuteera, 3rd Stage, Banashankar...",Addhuri Udupi Bhojana,No,No,3.7/5,88,+91 9620009302,Banashankari,Quick Bites,Masala Dosa,"South Indian, North Indian",300,"[('Rated 4.0', ""RATED\n Great food and proper...",[],Buffet,Banashankari
4,https://www.zomato.com/bangalore/grand-village...,"10, 3rd Floor, Lakshmi Associates, Gandhi Baza...",Grand Village,No,No,3.8/5,166,+91 8026612447\r\n+91 9901210005,Basavanagudi,Casual Dining,"Panipuri, Gol Gappe","North Indian, Rajasthani",600,"[('Rated 4.0', 'RATED\n Very good restaurant ...",[],Buffet,Banashankari

In [3]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51717 entries, 0 to 51716
Data columns (total 17 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   url                          51717 non-null  object
 1   address                      51717 non-null  object
 2   name                         51717 non-null  object
 3   online_order                 51717 non-null  object
 4   book_table                   51717 non-null  object
 5   rate                         43942 non-null  object
 6   votes                        51717 non-null  int64
 7   phone                        50509 non-null  object
 8   location                     51696 non-null  object
 9   rest_type                    51490 non-null  object
 10  dish_liked                   23639 non-null  object
 11  cuisines                     51672 non-null  object
 12  approx_cost(for two people)  51371 non-null  object
 13  reviews_list                 51717 non-null  object
 14  menu_item                    51717 non-null  object
 15  listed_in(type)              51717 non-null  object
 16  listed_in(city)              51717 non-null  object
dtypes: int64(1), object(16)
memory usage: 6.7+ MB

In [4]:
dataset.describe()

              votes
count  51717.000000
mean     283.697527
std      803.838853
min        0.000000
25%        7.000000
50%       41.000000
75%      198.000000
max    16832.000000

In [12]:

dataset["rate"] = dataset["rate"].str.replace("/5" ,"")
dataset.head()
dataset["rate"] = pd.to_numeric(dataset["rate"] , errors= "coerce")
dataset["rate"].info()

AttributeError: Can only use .str accessor with string values!

In [13]:
dataset["rate"].info()

<class 'pandas.core.series.Series'>
RangeIndex: 51717 entries, 0 to 51716
Series name: rate
Non-Null Count  Dtype
--------------  -----
41665 non-null  float64
dtypes: float64(1)
memory usage: 404.2 KB

In [33]:
#IQR method 

q1_value = dataset["rate"].quantile(0.25)
q2_value = dataset["rate"].quantile(0.50)
q3_value = dataset["rate"].quantile(0.75)

print( q1_value , q2_value, q3_value)

IQR = 1.5 * (q3_value - q1_value)

lowerb = q1_value - IQR
upperb = q3_value + IQR

print("\n" , lowerb , upperb)

outliers =((dataset["rate"] < lowerb ) | (dataset["rate"] > upperb)).sum()


outliers1 =  dataset["rate"][(dataset["rate"] < lowerb ) | (dataset["rate"] > upperb)]

null_Values = dataset["rate"].isnull().sum()
print(f"we have total {outliers} outliers" )

print(f"we have total {null_Values} null values" )

print(outliers1.index)

3.4 3.7 4.0

 2.5 4.9
we have total 187 outliers
we have total 10052 null values
Index([ 1532,  1570,  1573,  1637,  1647,  2028,  2030,  2044,  2048,  2121,
       ...
       48425, 48812, 49168, 49208, 49409, 49415, 49750, 49919, 49964, 50054],
      dtype='int64', length=187)

2. Create a boxplot for the 'order_amount' column from a Swiggy orders dataset using matplotlib, and visually identify any outliers present.

        Hint: Use plt.boxplot() and label your axes for clarity.

## Not taught yet markdown large to remember


3. Apply winsorization to the 'transaction_amount' column in a Paytm transactions DataFrame to cap all values above the 95th percentile and below the 5th percentile, then display the updated column statistics.

In [41]:
dataset1 = pd.read_csv("F:\Tops_assignment\Python_Library\datasets\paytm_transactions_100_with_outliers.csv")
dataset1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Transaction_ID      100 non-null    object
 1   User_ID             100 non-null    object
 2   Payment_Mode        100 non-null    object
 3   Merchant            100 non-null    object
 4   Transaction_Amount  100 non-null    int64
 5   Status              100 non-null    object
dtypes: int64(1), object(5)
memory usage: 4.8+ KB

In [42]:


q1_value = dataset1["Transaction_Amount"].quantile(0.05)
q2_value = dataset1["Transaction_Amount"].quantile(0.50)
q3_value = dataset1["Transaction_Amount"].quantile(0.95)

print( q1_value , q2_value, q3_value)

IQR = 1.5 * (q3_value - q1_value)

lowerb = q1_value - IQR
if lowerb < 0:
    lowerb = 0
upperb = q3_value + IQR


print("\n" , lowerb , upperb)



print(dataset1["Transaction_Amount"].describe())

outliers = dataset1["Transaction_Amount"][(dataset1["Transaction_Amount"]<lowerb) | (dataset1["Transaction_Amount"]>upperb)]


dataset1["Transaction_Amount"] = dataset1["Transaction_Amount"].clip(lower= lowerb , upper=upperb)

print(dataset1["Transaction_Amount"].describe())

238.5 2852.0 7212.949999999872

 0 17674.62499999968
count       100.000000
mean       8709.710000
std       31201.443298
min          66.000000
25%        1286.750000
50%        2852.000000
75%        4046.750000
max      250000.000000
Name: Transaction_Amount, dtype: float64
count      100.000000
mean      3343.441250
std       3602.023926
min         66.000000
25%       1286.750000
50%       2852.000000
75%       4046.750000
max      17674.625000
Name: Transaction_Amount, dtype: float64


4. You have a DataFrame of Flipkart product prices stored as strings with currency symbols (e.g., '₹1,299'). Convert this column to numeric type using pandas, ensuring all non-numeric characters are removed.

        Hint: Use str.replace() and astype().

In [46]:
### i had done this thinhg on ratings 

dataset = pd.read_csv("F:\Tops_assignment\Python_Library\datasets\zomato.csv\zomato.csv")
dataset["rate"] = dataset["rate"].str.replace("/5" ,"")
dataset.head()
dataset["rate"] = pd.to_numeric(dataset["rate"] , errors= "coerce")
print(dataset["rate"].info())
print(dataset["rate"].head())

<class 'pandas.core.series.Series'>
RangeIndex: 51717 entries, 0 to 51716
Series name: rate
Non-Null Count  Dtype
--------------  -----
41665 non-null  float64
dtypes: float64(1)
memory usage: 404.2 KB
None
0    4.1
1    4.1
2    3.8
3    3.7
4    3.8
Name: rate, dtype: float64


5. Fix the following code snippet where the 'is_premium' column in a Spotify user DataFrame is a mix of boolean, string, and integer types. Convert the entire column to boolean type, treating 'True', 1, and 'yes' as True,
and everything else as False.

In [47]:
import numpy as np

In [3]:
np.random.seed(42)

df = pd.DataFrame({
    "user_id": range(1, 101),
    "is_premium": np.random.choice(
        [True, False, "yes", "no", 1, 0],
        size=100
    )
})

print(df.head(10))

   user_id is_premium
0        1         no
1        2          1
2        3        yes
3        4          1
4        5          1
5        6      False
6        7        yes
7        8        yes
8        9        yes
9       10          1

In [ ]:
df["is_premium"] = df["is_premium"].str.replace("yes" ,"True")
df["is_premium"] = df["is_premium"].str.replace("True" ,"1")
print(df.head(10))

   user_id is_premium
0        1         no
1        2          1
2        3          1
3        4          1
4        5          1
5        6      False
6        7          1
7        8          1
8        9          1
9       10          1

In [4]:
## best way 

df["is_premium"] = df["is_premium"].apply(
    lambda x: str(x).lower() in ["true", "1", "yes"]
)

print(df.head(15))

    user_id  is_premium
0         1       False
1         2        True
2         3        True
3         4        True
4         5        True
5         6       False
6         7        True
7         8        True
8         9        True
9        10        True
10       11       False
11       12        True
12       13       False
13       14        True
14       15       False