SESSION 8- Data Cleaning (Part 3: Duplicates, Typos, Consistency)Topics Covered:Detecting duplicatesduplicated(), value_counts()Removing
duplicatesdrop_duplicates()Fixing typos in categorical columnsUsing replace()Fuzzy matching overviewEnsuring consistencyCapitalization, trimming
whitespaceUnifying category formats (e.g., Yes/No ?1/0)

In [1]:
import pandas as pd



TASKS


1. Download a small sample of your recent Zomato order history as a CSV (or create a mock CSV with restaurant names and order dates), then use pandas' duplicated() function to find and print any duplicate orders
based on restaurant name and date.

In [3]:
dataset1 = pd.read_csv("F:\Tops_assignment\Python_Library\datasets\zomato.csv\zomato.csv")

In [4]:
dataset1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51717 entries, 0 to 51716
Data columns (total 17 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   url                          51717 non-null  object
 1   address                      51717 non-null  object
 2   name                         51717 non-null  object
 3   online_order                 51717 non-null  object
 4   book_table                   51717 non-null  object
 5   rate                         43942 non-null  object
 6   votes                        51717 non-null  int64
 7   phone                        50509 non-null  object
 8   location                     51696 non-null  object
 9   rest_type                    51490 non-null  object
 10  dish_liked                   23639 non-null  object
 11  cuisines                     51672 non-null  object
 12  approx_cost(for two people)  51371 non-null  object
 13  reviews_list                 51717 non-null  object
 14  menu_item                    51717 non-null  object
 15  listed_in(type)              51717 non-null  object
 16  listed_in(city)              51717 non-null  object
dtypes: int64(1), object(16)
memory usage: 6.7+ MB

In [10]:
duplicatess = dataset1[dataset1.duplicated(subset = ["phone"] ,  keep = "first")]

print(duplicatess)

                                                     url  \
14     https://www.zomato.com/SanchurroBangalore?cont...
44     https://www.zomato.com/bangalore/onesta-banash...
104    https://www.zomato.com/bangalore/cafe-nova-ban...
145    https://www.zomato.com/bangalore/anna-kuteera-...
193    https://www.zomato.com/bangalore/caf%C3%A9-dow...
...                                                  ...
51712  https://www.zomato.com/bangalore/best-brews-fo...
51713  https://www.zomato.com/bangalore/vinod-bar-and...
51714  https://www.zomato.com/bangalore/plunge-sherat...
51715  https://www.zomato.com/bangalore/chime-sherato...
51716  https://www.zomato.com/bangalore/the-nest-the-...

                                                 address  \
14     1112, Next to KIMS Medical College, 17th Cross...
44     2469, 3rd Floor, 24th Cross, Opposite BDA Comp...
104    101, Water Tank Road, 2nd Block, 3rd Stage, Ba...
145    21, 80 Feet Road, 3rd Phase, 4th Block, 3rd St...
193    12,29 Near PES University Back Gate, D'Souza N...
...                                                  ...
51712  Four Points by Sheraton Bengaluru, 43/3, White...
51713  Number 10, Garudachar Palya, Mahadevapura, Whi...
51714  Sheraton Grand Bengaluru Whitefield Hotel & Co...
51715  Sheraton Grand Bengaluru Whitefield Hotel & Co...
51716  ITPL Main Road, KIADB Export Promotion Industr...

                                                    name online_order  \
14                                       San Churro Cafe          Yes
44                                                Onesta          Yes
104                                            CAFE NOVA           No
145                                         Anna Kuteera          Yes
193    CafÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ© Down The A...          Yes
...                                                  ...          ...
51712  Best Brews - Four Points by Sheraton Bengaluru...           No
51713                           Vinod Bar And Restaurant           No
51714  Plunge - Sheraton Grand Bengaluru Whitefield H...           No
51715  Chime - Sheraton Grand Bengaluru Whitefield Ho...           No
51716                       The Nest - The Den Bengaluru           No

      book_table    rate  votes                           phone  \
14            No   3.8/5    918                  +91 9663487993
44           Yes   4.6/5   2556    080 48653961\r\n080 48655715
104           No   3.2/5     11                  +91 8971090261
145           No   4.0/5    771                  +91 9620009302
193           No   4.1/5    402  080 26724489\r\n+91 7406048982
...          ...     ...    ...                             ...
51712         No  3.6 /5     27                    080 40301477
51713         No     NaN      0                  +91 8197675843
51714         No     NaN      0                             NaN
51715        Yes  4.3 /5    236                    080 49652769
51716         No  3.4 /5     13                  +91 8071117272

                         location            rest_type  \
14                   Banashankari  Cafe, Casual Dining
44                   Banashankari  Casual Dining, Cafe
104                  Banashankari                 Cafe
145                  Banashankari        Casual Dining
193                  Banashankari                 Cafe
...                           ...                  ...
51712                  Whitefield                  Bar
51713                  Whitefield                  Bar
51714                  Whitefield                  Bar
51715  ITPL Main Road, Whitefield                  Bar
51716  ITPL Main Road, Whitefield   Bar, Casual Dining

                                              dish_liked  \
14     Churros, Cannelloni, Minestrone Soup, Hot Choc...
44     Farmhouse Pizza, Chocolate Banana, Virgin Moji...
104                                                  NaN
145    Panner Tikka, Kulfi, Coffee, Pav Bhaji, Carrot...
193    Waffles, Pasta, Crispy Chicken, Honey Chilli C...
...                                                  ...
51712                                                NaN
51713                                                NaN
51714                                                NaN
51715                       Cocktails, Pizza, Buttermilk
51716                                                NaN

                                     cuisines approx_cost(for two people)  \
14                     Cafe, Mexican, Italian                         800
44                       Pizza, Cafe, Italian                         600
104                              Cafe, Bakery                         600
145       South Indian, North Indian, Chinese                         450
193                                      Cafe                         500
...                                       ...                         ...
51712                             Continental                       1,500
51713                             Finger Food                         600
51714                             Finger Food                       2,000
51715                             Finger Food                       2,500
51716  Finger Food, North Indian, Continental                       1,500

                                            reviews_list  \
14     [('Rated 3.0', "RATED\n  Ambience is not that ...
44     [('Rated 5.0', 'RATED\n  I personally really l...
104    [('Rated 1.0', "RATED\n  No ventilation. Smoke...
145    [('Rated 3.0', 'RATED\n  This our go to place ...
193    [('Rated 4.0', 'RATED\n  We ended up here on a...
...                                                  ...
51712  [('Rated 5.0', "RATED\n  Food and service are ...
51713                                                 []
51714                                                 []
51715  [('Rated 4.0', 'RATED\n  Nice and friendly pla...
51716  [('Rated 5.0', 'RATED\n  Great ambience , look...

                                               menu_item listed_in(type)  \
14                                                    []           Cafes
44                                                    []        Delivery
104                                                   []        Delivery
145    ['Vada', 'Ghee Masala Dosa', 'Onion Dosa', 'Ra...        Delivery
193                                                   []        Delivery
...                                                  ...             ...
51712                                                 []   Pubs and bars
51713                                                 []   Pubs and bars
51714                                                 []   Pubs and bars
51715                                                 []   Pubs and bars
51716                                                 []   Pubs and bars

      listed_in(city)
14       Banashankari
44       Banashankari
104      Banashankari
145      Banashankari
193      Banashankari
...               ...
51712      Whitefield
51713      Whitefield
51714      Whitefield
51715      Whitefield
51716      Whitefield

[36790 rows x 17 columns]


2. Given a list of Flipkart product reviews with some duplicate entries, use value_counts() in pandas to identify which review texts are repeated most often and display the top 3 most common duplicate reviews.

In [9]:
dataset2 = pd.read_excel("F:/Tops_assignment/Python_Library/datasets/flipkart_product_excel/flipkart_product_listings_10000.xlsx")
dataset2.head()
dataset2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Product_ID    10000 non-null  object
 1   Product_Name  10000 non-null  object
 2   Category      10000 non-null  object
 3   Brand         10000 non-null  object
 4   Price_INR     10000 non-null  int64
 5   Rating        10000 non-null  float64
 6   Reviews       10000 non-null  int64
dtypes: float64(1), int64(2), object(4)
memory usage: 547.0+ KB

In [10]:
reviews = [
    "Good product",
    "Excellent quality",
    "Worth the price",
    "Bad packaging",
    "Highly recommended",
    "Good product",
    "Excellent quality",
    "Good product",
    "Worth the price",
    "Good product"
] * 100  # Creates 100 rows

dataset2["reviews"]  = pd.DataFrame({"reviews" : reviews})

In [11]:
dataset2.head()

,Product_ID,Product_Name,Category,Brand,Price_INR,Rating,Reviews,reviews
0,FK00001,Product 1,Fashion,Samsung,19732,4.1,1839,Good product
1,FK00002,Product 2,Electronics,LG,90294,3.7,2544,Excellent quality
2,FK00003,Product 3,Electronics,Puma,23735,3.5,2157,Worth the price
3,FK00004,Product 4,Fashion,Apple,45023,3.7,2762,Bad packaging
4,FK00005,Product 5,Beauty,Boat,74025,4.5,3335,Highly recommended

In [17]:
review_counts = dataset2["reviews"].value_counts().head(3)
print(review_counts)

reviews
Good product         400
Excellent quality    200
Worth the price      200
Name: count, dtype: int64


3. Create a DataFrame with mock data for Spotify playlists, including playlist names and creator usernames, where some rows are exact duplicates. Use drop_duplicates() to remove duplicate playlists and print the cleaned
DataFrame.

In [20]:

data = {
    "playlist_name": [
        "Chill Vibes",
        "Workout Mix",
        "Top Hits 2025",
        "Chill Vibes",
        "Road Trip",
        "Workout Mix",
        "LoFi Beats",
        "Party Songs",
        "Road Trip",
        "Top Hits 2025"
    ],
    "creator_username": [
        "aman123",
        "priya_music",
        "rahul_songs",
        "aman123",
        "neha_travel",
        "priya_music",
        "jay_lofi",
        "karan_party",
        "neha_travel",
        "rahul_songs"
    ]
}

df = pd.DataFrame(data)

print(df)
print("-----------------------------------------")
df = df.drop_duplicates()
print(df)

   playlist_name creator_username
0    Chill Vibes          aman123
1    Workout Mix      priya_music
2  Top Hits 2025      rahul_songs
3    Chill Vibes          aman123
4      Road Trip      neha_travel
5    Workout Mix      priya_music
6     LoFi Beats         jay_lofi
7    Party Songs      karan_party
8      Road Trip      neha_travel
9  Top Hits 2025      rahul_songs
-----------------------------------------
   playlist_name creator_username
0    Chill Vibes          aman123
1    Workout Mix      priya_music
2  Top Hits 2025      rahul_songs
4      Road Trip      neha_travel
6     LoFi Beats         jay_lofi
7    Party Songs      karan_party


4. Suppose you have a DataFrame of Instagram usernames where some entries have typos (like 'insta_queen', 'insta-queen', 'instaqueen'). Use the replace() function to standardize all these variants to 'instaqueen'.

In [22]:
list1 = ["insta_queen" , "insta-queen ", "instaqueen"]*100

df = pd.DataFrame({"val":list1})

print(df)

df["val"] = df["val"].str.replace("_","")
df["val"] = df["val"].str.replace("-","")
df["val"] = df["val"].str.replace(" ","")
df["val"]

              val
0     insta_queen
1    insta-queen
2      instaqueen
3     insta_queen
4    insta-queen
..            ...
295  insta-queen
296    instaqueen
297   insta_queen
298  insta-queen
299    instaqueen

[300 rows x 1 columns]

0      instaqueen
1      instaqueen
2      instaqueen
3      instaqueen
4      instaqueen
          ...
295    instaqueen
296    instaqueen
297    instaqueen
298    instaqueen
299    instaqueen
Name: val, Length: 300, dtype: object


5. You have a DataFrame column for payment status from a Paytm-like app with mixed values: 'Yes', 'yes', 'Y', 'No', 'no', 'N', and some with extra spaces. Write code to unify this column so all paid statuses become 1 and all
unpaid statuses become 0, trimming whitespace and fixing capitalization where needed.

        Hint: Use str.strip(, str.lower0), and map/replace methods in pandas.

In [25]:

data = {
    "payment_status": [
        "Yes", "yes", "Y", "No", "no", "N",
        " Yes ", " no ", "Y ", " N", "yes "
    ]
}

df = pd.DataFrame(data)

print("Before:")
print(df)

df["payment_status"] = df["payment_status"].str.strip().str.lower().map({
    "yes" :1,
    "y":1,
    "no" :0,
    "n":0
})

df

Before:
   payment_status
0             Yes
1             yes
2               Y
3              No
4              no
5               N
6            Yes
7             no
8              Y
9               N
10           yes

    payment_status
0                1
1                1
2                1
3                0
4                0
5                0
6                1
7                0
8                1
9                0
10               1